name: Gatsby Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.SECRETKEY}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "menon.abh@northeastern.edu"
          git config --global user.name "justbee007"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
         yarn install
      - name: Deploy
        run: npm run deploy:ci