name: Gatsby Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.SECRETKEY}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - name: Deploy 🚀
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public
          repositoryName: deploy_to_repo #Skip this if deploying to same repo
          token: ${{ secrets.GH_TOKEN}} #Skip this when deploying to
          run: npm run deploy
